
steps:

- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.401' 

- task: DotNetCoreCLI@2
  inputs:
    command: build

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'test/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'

- task: PublishBuildArtifacts@1
  displayName: publish artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
