
steps:

- displayName: install dotnet 2.1.401
  task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.1.401' 

- displayName: dotnet build
  task: DotNetCoreCLI@2
  inputs:
    command: build

- displayName: dotnet test
  task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'test/**/*.csproj'

- displayName: dotnet pack
  task: DotNetCoreCLI@2
  inputs:
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'

- displayName: dotnet nuget push
  task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: nuget
    arguments: push $(System.ArtifactStagingDirectory)/packages/*.nupkg --source https://www.myget.org/F/lodejard-greeting/api/v3/index.json --no-service-endpoint --api-key $(myget-apikey)

- displayName: publish artifacts
  task: PublishBuildArtifacts@1
  displayName: publish artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
